In [1]:
import os
import pandas as pd

In [2]:
# Where our data lives
CSV_PATH = os.path.join('data', 'artwork_data.csv')
CSV_PATH

'data\\artwork_data.csv'

In [3]:
# Read just 5 rows to see what's there
df = pd.read_csv(CSV_PATH, nrows=5)
df

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

In [4]:
# Specify an Index
df = pd.read_csv(CSV_PATH, nrows=5, index_col='id')
df

,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
id,,,,,,,,,,,,,,,,,,,
1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

In [5]:
# Limit columns
df = pd.read_csv(CSV_PATH, nrows=5, index_col='id', usecols=['id', 'artist'])
df

              artist
id
1035   Blake, Robert
1036   Blake, Robert
1037   Blake, Robert
1038   Blake, Robert
1039  Blake, William

In [6]:
# All columns that we need
COLS_TO_USE = ['id', 'artist', 'title', 'medium', 'year', 'acquisitionYear', 'height', 'width', 'units']

In [7]:
# Proper data loading
df = pd.read_csv(CSV_PATH, index_col='id', usecols=COLS_TO_USE)
df

C:\Users\micro\AppData\Local\Temp\ipykernel_19620\3736523637.py:2: DtypeWarning: Columns (9,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(CSV_PATH, index_col='id', usecols=COLS_TO_USE)

,artist,title,medium,year,acquisitionYear,width,height,units
id,,,,,,,,
1035,"Blake, Robert",A Figure Bowing before a Seated Old Man with h...,"Watercolour, ink, chalk and graphite on paper....",NaN,1922.0,394,419.0,mm
1036,"Blake, Robert","Two Drawings of Frightened Figures, Probably f...",Graphite on paper,NaN,1922.0,311,213.0,mm
1037,"Blake, Robert",The Preaching of Warning. Verso: An Old Man En...,Graphite on paper. Verso: graphite on paper,1785.0,1922.0,343,467.0,mm
1038,"Blake, Robert",Six Drawings of Figures with Outstretched Arms,Graphite on paper,NaN,1922.0,318,394.0,mm
1039,"Blake, William",The Circle of the Lustful: Francesca da Rimini...,Line engraving on paper,1826.0,1919.0,243,335.0,mm
...,...,...,...,...,...,...,...,...
122960,"P-Orridge, Genesis",Larvae (from Tampax Romana),"Perspex, Wood, hairpiece, tampon and human blood",1975,2013.0,305,305.0,mm
122961,"P-Orridge, Genesis",Living Womb (from Tampax Romana),"Wood, Perspex, plastic, photograph on paper, t...",1976,2013.0,305,305.0,mm
121181,"Hatoum, Mona",Present Tense,Soap and glass beads,1996,2013.0,45,2410.0,mm
112306,"Creed, Martin",Work No. 227: The lights going on and off,Gallery lighting,2000,2013.0,NaN,NaN,NaN
127035,"Brunias, Agostino",Dancing Scene in the West Indies,Oil paint on canvas,1764,2013.0,508,660.0,mm

In [8]:
# Save for later
df.to_pickle(os.path.join('data', 'artwork_data.pickle'))

In [9]:
# Example usage of from_records method
records = [("Espresso", "5$"), ("Flat White", "10$")]

In [10]:
pd.DataFrame.from_records(records)

            0    1
0    Espresso   5$
1  Flat White  10$

In [11]:
pd.DataFrame.from_records(records, columns=["Coffee", "Price"])

       Coffee Price
0    Espresso    5$
1  Flat White   10$

In [12]:
import json

In [13]:
def get_record_from_file(file_path, keys_to_use):
    """ Process single json file and return a tuple
    containing specific fields."""

    with open(file_path) as artwork_file:
        content = json.load(artwork_file)
            
    record = []    
    for field in keys_to_use:
        record.append(content[field])
        
    return tuple(record)

In [14]:
KEYS_TO_USE = ['id', 'all_artists', 'title', 'medium', 'dateText', 'acquisitionYear', 'height', 'width', 'units']

In [15]:
# Single file processing function demo
SAMPLE_JSON = os.path.join('data', 'artworks', 'a', '000', 'a00001-1035.json')
sample_record = get_record_from_file(SAMPLE_JSON, KEYS_TO_USE)
sample_record

(1035,
 'Robert Blake',
 'A Figure Bowing before a Seated Old Man with his Arm Outstretched in Benediction. Verso: Indecipherable Sketch',
 'Watercolour, ink, chalk and graphite on paper. Verso: graphite on paper',
 'date not known',
 1922,
 '419',
 '394',
 'mm')

In [16]:
def read_artworks_from_json(keys_to_use):
    """ Traverse the directories with JSON files.
    For first file in each directory call function
    for processing single file and go to the next
    directory.
    """
    JSON_ROOT = os.path.join('data', 'artworks')
    artworks = []
    for root, _, files in os.walk(JSON_ROOT):
        for f in files:
            if f.endswith('json'):
                record = get_record_from_file(
                            os.path.join(root, f),
                            keys_to_use)
                artworks.append(record)
            break
        
    df = pd.DataFrame.from_records(artworks,
                                   columns=keys_to_use,
                                   index="id")
    return df

In [17]:
df = read_artworks_from_json(KEYS_TO_USE)
df

,all_artists,title,medium,dateText,acquisitionYear,height,width,units
id,,,,,,,,
1035,Robert Blake,A Figure Bowing before a Seated Old Man with h...,"Watercolour, ink, chalk and graphite on paper....",date not known,1922,419,394,mm
20230,"Sir Edward Coley Burne-Jones, Bt",Study of Heads for a Pietà,Graphite and chalk on paper,date not known,1927,154,136,mm
6725,Arthur Boyd Houghton,[title not known],Graphite on paper,date not known,1922,,,
7330,George Jones,[title not known],Ink on paper,date not known,1888,,,
7430,George Jones,[title not known],Ink on paper,date not known,1888,,,
...,...,...,...,...,...,...,...,...
118532,Trevor Bell,Place,Acrylic paint on paper,1989,2012,980,750,mm
117815,Jiro Takamatsu,Shadow,Graphite on paper,1965,2012,181,260,mm
117484,Shelagh Cluett,Flux III,"Steel, bitumen, latex, clay and cotton string",1979,2012,950,2430,mm
89762,Robert Mangold,Red Wall,Oil paint on fibreboard,1965,2013,2450,2450,mm
123531,"Birdhead (Ji Weiyu, born 1980; Song Tao, born ...",Welcome to Birdhead World Again,"6 photographs, cellulose print, black and whit...",2011,2013,,,